seed: 1
xp_name: test_cavity

environment:
  name: cavity
  parameters:
    dict_pde_config:
      dt: 1.0e-4
      reynolds: 7500
      n_steps: 1.0e+6

    dict_callback_config:
      dict_paraview_callback:
        interval: 10
      dict_log_callback:
          interval: 10
